import { collection, doc, setDoc } from 'firebase/firestore';
import { db } from './firebase.js';

// Función para cargar las preguntas en Firebase Firestore
const cargarPreguntas = async () => {
    const preguntas = [
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser invisible', opcion2: 'Ser capaz de volar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser rico', opcion2: 'Ser famoso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el mejor amigo de un famoso', opcion2: 'Ser el peor enemigo de un famoso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el mejor en algo que no te gusta', opcion2: 'Ser el peor en algo que te gusta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener el poder de leer mentes', opcion2: 'Tener el poder de ser invisible' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser millonario pero siempre trabajar', opcion2: 'Ser pobre pero nunca tener que trabajar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Viajar al pasado', opcion2: 'Viajar al futuro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser extremadamente inteligente pero no tener sentido del humor', opcion2: 'Ser muy divertido pero no ser muy inteligente' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de volverse invisible cuando nadie te esté mirando', opcion2: 'Tener la capacidad de volar pero solo a una altura máxima de 1 metro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser siempre el centro de atención', opcion2: 'Pasar desapercibido en cualquier situación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de controlar el clima', opcion2: 'Tener la capacidad de hablar con los animales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser extremadamente rico pero nunca encontrar el amor verdadero', opcion2: 'Encontrar el amor verdadero pero siempre tener problemas financieros' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser conocido por algo negativo pero ser millonario', opcion2: 'Ser desconocido pero amado por todos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Poder leer todos los libros del mundo en un instante', opcion2: 'Poder hablar todos los idiomas del mundo de forma fluida' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de detener el tiempo', opcion2: 'Tener la capacidad de viajar en el tiempo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el mejor en tu profesión pero odiar lo que haces', opcion2: 'Hacer lo que amas pero no ser reconocido por ello' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de controlar los sueños', opcion2: 'Tener la capacidad de cambiar el pasado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser un genio incomprendido', opcion2: 'Ser una persona promedio pero muy feliz' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser teletransportado instantáneamente a cualquier lugar', opcion2: 'Tener la capacidad de leer la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los animales', opcion2: 'Tener la capacidad de hablar todos los idiomas humanos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser capaz de ver 10 minutos en el futuro', opcion2: 'Ser capaz de ver 150 años en el futuro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el mejor jugador de videojuegos del mundo', opcion2: 'Ser el mejor deportista en tu deporte favorito' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de detener el envejecimiento', opcion2: 'Tener la capacidad de curar cualquier enfermedad' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de teletransportarte a cualquier lugar del mundo', opcion2: 'Tener la capacidad de viajar en el tiempo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser un experto en todas las artes marciales', opcion2: 'Ser un maestro en todas las disciplinas musicales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de comunicarte con los seres extraterrestres', opcion2: 'Tener la capacidad de explorar los océanos más profundos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de controlar los elementos naturales (agua, fuego, aire, tierra)', opcion2: 'Tener la capacidad de controlar las mentes de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el personaje principal de tu videojuego favorito', opcion2: 'Vivir en el mundo real pero con la capacidad de usar poderes mágicos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de viajar instantáneamente a cualquier libro y experimentar su historia', opcion2: 'Tener la capacidad de crear tus propias historias con solo pensarlo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer todos los libros del mundo en un instante', opcion2: 'Tener la capacidad de absorber todo el conocimiento del mundo con solo tocar un objeto' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser invisible pero hacer un sonido fuerte cada vez que te mueves', opcion2: 'Ser capaz de volar pero solo a baja velocidad' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser el mejor chef del mundo', opcion2: 'Ser el mejor músico del mundo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de predecir el futuro', opcion2: 'Tener la capacidad de cambiar el pasado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser inmune a todas las enfermedades', opcion2: 'Tener una increíble resistencia física' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser capaz de entender y hablar con las plantas', opcion2: 'Ser capaz de comunicarte con los animales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de controlar y manipular el clima', opcion2: 'Tener la capacidad de controlar y manipular los sueños' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de teletransportarte a cualquier lugar del pasado', opcion2: 'Tener la capacidad de teletransportarte a cualquier lugar del futuro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de regresar en el tiempo y corregir tus errores', opcion2: 'Tener la capacidad de ver el futuro y saber qué decisiones tomar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer realidad cualquier deseo tuyo', opcion2: 'Tener la capacidad de hacer realidad cualquier deseo de los demás' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Ser conocido por haber descubierto una cura para una enfermedad mortal', opcion2: 'Ser conocido por haber inventado una tecnología revolucionaria' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en rima', opcion2: 'Siempre tener que cantar lo que dices' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como un robot', opcion2: 'Siempre tener que moverte como un animal' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener siempre una melodía pegajosa en la cabeza', opcion2: 'Nunca más poder escuchar música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre sentirte demasiado caliente', opcion2: 'Siempre sentirte demasiado frío' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación solo en memes', opcion2: 'Tener una conversación solo en emojis' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos', opcion2: 'Nunca más poder escuchar un chiste' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una mascota dinosaurio', opcion2: 'Tener una mascota dragón' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que bailar cuando escuchas música', opcion2: 'Siempre tener que hacer muecas cuando hablas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos inanimados', opcion2: 'Tener la capacidad de entender el lenguaje de las abejas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas unicornio', opcion2: 'Tener un guardaespaldas ninja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que andar en bicicleta para moverte', opcion2: 'Siempre tener que saltar como un canguro para moverte' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un clon de ti que haga todas las tareas aburridas', opcion2: 'Tener un clon de ti que te siga y repita todo lo que haces' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener un fondo musical en tu vida', opcion2: 'Siempre tener una audiencia que aplaude después de cada cosa que haces' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender el lenguaje de los bebés', opcion2: 'Tener la capacidad de comunicarte con los animales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un teléfono que solo pueda enviar gifs', opcion2: 'Tener un teléfono que solo pueda enviar memes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que usar un sombrero extravagante', opcion2: 'Siempre tener que usar zapatos que suenan con cada paso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar cada palabra con "meow"', opcion2: 'Siempre tener que reemplazar cada palabra con "quack"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar de color como un camaleón', opcion2: 'Tener la capacidad de brillar en la oscuridad como una luciérnaga' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte haciendo moonwalk', opcion2: 'Siempre tener que moverte como si estuvieras en una pasarela' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los pensamientos de los gatos', opcion2: 'Tener la capacidad de entender los pensamientos de los perros' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener una canción de fondo cuando hablas', opcion2: 'Nunca más poder escuchar tu voz' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer preguntas divertidas a las personas', opcion2: 'Tener la capacidad de hacer imitaciones perfectas de celebridades' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte al ritmo de la música que escuchas', opcion2: 'Siempre tener que tararear la melodía que está en tu cabeza' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier objeto en una versión miniatura', opcion2: 'Tener la capacidad de transformar cualquier objeto en una versión gigante' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que saludar a las personas con un saludo inventado', opcion2: 'Siempre tener que saludar a las personas con un baile improvisado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas se iluminen al tocarlas', opcion2: 'Tener la capacidad de hacer que las cosas desaparezcan al tocarlas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en rimas simples', opcion2: 'Siempre tener que hablar en palabras inventadas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer las conversaciones de las plantas', opcion2: 'Tener la capacidad de entender los mensajes ocultos en las nubes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar con voz de bebé', opcion2: 'Siempre tener que hablar con voz de anciano' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego retro', opcion2: 'Siempre tener que moverte como si estuvieras en un baile de TikTok' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un viaje gratis a cualquier lugar del mundo cada año', opcion2: 'Tener un encuentro con tu celebridad favorita una vez en tu vida' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un disfraz extravagante en público', opcion2: 'Siempre tener que llevar ropa al revés en público' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber el nombre de cualquier persona que veas', opcion2: 'Tener la capacidad de saber el secreto más profundo de cualquier persona que veas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar una palabra en cada frase con "cacahuete"', opcion2: 'Siempre tener que reemplazar una palabra en cada frase con "piña"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', opcion2: 'Tener un espejo que te muestra cómo serás en 20 años' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que repetir la última palabra que dices', opcion2: 'Siempre tener que hacer un chasquido de dedos después de cada frase' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender el lenguaje de los pájaros', opcion2: 'Tener la capacidad de entender el lenguaje de los insectos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en acertijos', opcion2: 'Siempre tener que hablar en trabalenguas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación con un alienígena durante una hora', opcion2: 'Tener una conversación con un fantasma durante una hora' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que correr en cámara lenta', opcion2: 'Siempre tener que hablar en cámara lenta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier objeto en chocolate', opcion2: 'Tener la capacidad de transformar cualquier objeto en caramelo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que usar una corona dondequiera que vayas', opcion2: 'Siempre tener que usar un sombrero de vaquero dondequiera que vayas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comer tu comida favorita en cada comida', opcion2: 'Nunca más poder comer tu comida favorita' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación con los animales solo una vez', opcion2: 'Tener la capacidad de hablar todos los idiomas humanos por un día' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en lenguaje de señas', opcion2: 'Siempre tener que comunicarte a través de mímica' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un archivo con todos tus pensamientos pasados', opcion2: 'Tener un archivo con todos tus correos electrónicos enviados del futuro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una reverencia al saludar a alguien', opcion2: 'Siempre tener que hacer una pirueta al saludar a alguien' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que elegir entre hablar en verso o hablar en rima', opcion2: 'Siempre tener que hablar en un idioma extranjero al azar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los mensajes secretos de las palomas mensajeras', opcion2: 'Tener la capacidad de entender los mensajes secretos de los gatos callejeros' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar un chiste antes de hablar en serio', opcion2: 'Siempre tener que contar un hecho interesante antes de hablar en serio' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación con tu objeto inanimado favorito', opcion2: 'Tener una conversación con tu comida favorita antes de comerla' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que bailar en cualquier lugar donde escuches música', opcion2: 'Siempre tener que hacer un chiste cada vez que alguien hable contigo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un control remoto que funcione solo en personas', opcion2: 'Tener un control remoto que funcione solo en objetos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que elegir entre hablar en voz baja o gritar', opcion2: 'Siempre tener que hablar en un idioma desconocido' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de encontrar siempre un estacionamiento perfecto', opcion2: 'Tener la capacidad de evitar siempre las colas en cualquier lugar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un bigote falso', opcion2: 'Siempre tener que llevar una nariz roja de payaso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un sombrero que cambia de forma según tu estado de ánimo', opcion2: 'Tener zapatos que te hacen saltar más alto de lo normal' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte a través de señales de humo', opcion2: 'Siempre tener que comunicarte a través de señales de luz con una linterna' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con las plantas', opcion2: 'Tener la capacidad de entender el lenguaje de los objetos electrónicos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta cuando estás emocionado', opcion2: 'Siempre tener que moverte muy rápido cuando estás nervioso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una habitación con paredes de trampolín', opcion2: 'Tener una habitación con paredes de espejos distorsionados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar con voz de robot', opcion2: 'Siempre tener que hablar con voz de dibujo animado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un asistente personal invisible', opcion2: 'Tener un asistente personal robot' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una danza alegre cada vez que llueve', opcion2: 'Siempre tener que hacer una danza triste cada vez que sale el sol' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de traducir los ladridos de los perros', opcion2: 'Tener la capacidad de traducir los maullidos de los gatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener un séquito de pingüinos siguiéndote', opcion2: 'Siempre tener un séquito de flamencos siguiéndote' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un reloj que te muestra cuánto tiempo te queda de vida', opcion2: 'Tener un reloj que te muestra cuántos actos de bondad has realizado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer un salto mortal antes de sentarte en cualquier lugar', opcion2: 'Siempre tener que hacer un giro antes de levantarte de cualquier silla' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un cojín que siempre está en la temperatura perfecta', opcion2: 'Tener un cojín que emite sonidos relajantes cuando te sientas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tener una conversación seria con una marioneta', opcion2: 'Siempre tener que tener una conversación en tono cómico con un maniquí' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos inanimados', opcion2: 'Tener la capacidad de entender el lenguaje de las abejas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar una palabra en cada frase con "meow"', opcion2: 'Siempre tener que reemplazar una palabra en cada frase con "quack"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', opcion2: 'Tener un espejo que te muestra cómo serás en 20 años' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte haciendo moonwalk', opcion2: 'Siempre tener que moverte como si estuvieras en una pasarela' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender el lenguaje de los pájaros', opcion2: 'Tener la capacidad de entender el lenguaje de los insectos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en acertijos', opcion2: 'Siempre tener que hablar en trabalenguas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación con un alienígena durante una hora', opcion2: 'Tener una conversación con un fantasma durante una hora' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte al ritmo de la música que escuchas', opcion2: 'Siempre tener que tararear la melodía que está en tu cabeza' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier objeto en chocolate', opcion2: 'Tener la capacidad de transformar cualquier objeto en caramelo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que usar una corona dondequiera que vayas', opcion2: 'Siempre tener que usar un sombrero de vaquero dondequiera que vayas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los mensajes secretos de las palomas mensajeras', opcion2: 'Tener la capacidad de entender los mensajes secretos de los gatos callejeros' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar un chiste antes de hablar en serio', opcion2: 'Siempre tener que contar un hecho interesante antes de hablar en serio' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación con tu objeto inanimado favorito', opcion2: 'Tener una conversación con tu comida favorita antes de comerla' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener siempre un acompañante invisible que solo tú puedes ver', opcion2: 'Tener siempre una sombra que tiene su propia personalidad' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en rimas', opcion2: 'Siempre tener que hablar en jeroglíficos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas se iluminen al tocarlas', opcion2: 'Tener la capacidad de hacer que las cosas desaparezcan al tocarlas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que dar un salto antes de entrar a cualquier habitación', opcion2: 'Siempre tener que girar sobre ti mismo antes de sentarte en cualquier silla' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las nubes formen figuras específicas', opcion2: 'Tener la capacidad de cambiar el color del cielo a voluntad' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que saludar a las personas con una reverencia', opcion2: 'Siempre tener que saludar a las personas con un salto en el aire' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el sabor de cualquier comida a tu antojo', opcion2: 'Tener la capacidad de cambiar el olor de cualquier ambiente a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que andar a cuatro patas como un animal', opcion2: 'Siempre tener que saltar en un solo pie como un canguro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un periódico que siempre predice tu día futuro', opcion2: 'Tener un espejo que siempre muestra cómo te ves en tu día futuro' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el color de tu piel como un camaleón', opcion2: 'Tener la capacidad de cambiar el patrón de tu piel como un cebra' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en verso', opcion2: 'Siempre tener que hablar en onomatopeyas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que cambia el clima solo en tu ubicación', opcion2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación telepática con los animales', opcion2: 'Tener la capacidad de comunicarte con las plantas a través de canciones' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar tus pensamientos en voz alta', opcion2: 'Siempre tener que hablar en un idioma inventado por ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier conversación en una canción', opcion2: 'Tener la capacidad de convertir cualquier conversación en un poema' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', opcion2: 'Siempre tener que responder instantáneamente sin pensar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas gorila', opcion2: 'Tener un guardaespaldas flamenco' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', opcion2: 'Siempre tener que llevar un paraguas incluso en días despejados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una burbuja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', opcion2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', opcion2: 'Tener la capacidad de hacer que las cosas cambien de forma' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta durante las mañanas', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un video musical', opcion2: 'Siempre tener que moverte como si estuvieras en una película de acción' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un teletransportador que solo funciona si haces el moonwalk', opcion2: 'Tener un teletransportador que solo funciona si haces una pirueta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tatuaje temporal con un mensaje divertido', opcion2: 'Siempre tener que llevar un tatuaje temporal con un mensaje inspirador' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos electrónicos', opcion2: 'Tener la capacidad de comunicarte con las nubes a través de movimientos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que dar una pequeña actuación antes de tomar una foto', opcion2: 'Siempre tener que hacer una pose extravagante antes de tomar una foto' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en lenguaje de señas', opcion2: 'Siempre tener que comunicarte en lenguaje morse' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un sombrero que siempre reproduce música a tu alrededor', opcion2: 'Tener una bufanda que siempre te mantiene a la temperatura perfecta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos hablen como en las películas animadas', opcion2: 'Tener la capacidad de hacer que los objetos bailen como en los videos musicales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que responder preguntas solo en forma de preguntas', opcion2: 'Siempre tener que responder preguntas solo en forma de refranes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de teletransportarte a cualquier lugar, pero solo puedes llevar contigo objetos inútiles', opcion2: 'Tener la capacidad de volar, pero solo a baja velocidad y solo en círculos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar una cola de sirena en lugar de piernas', opcion2: 'Siempre tener que llevar orejas de conejo en lugar de orejas humanas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de controlar la gravedad solo en tu área cercana', opcion2: 'Tener la capacidad de controlar las corrientes de aire solo en tu área cercana' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que saludar a los extraños con una reverencia ninja', opcion2: 'Siempre tener que saludar a los extraños con un salto al estilo de Michael Jordan' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un retrato tuyo que envejece en lugar de tú', opcion2: 'Tener un espejo que refleja tu versión más feliz' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que bailar cada vez que escuchas música, sin importar el lugar', opcion2: 'Siempre tener que cantar cada vez que escuchas música, sin importar el lugar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una marioneta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en rimas', opcion2: 'Siempre tener que comunicarte en poesía épica' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un control remoto que solo funciona en personas', opcion2: 'Tener un control remoto que solo funciona en animales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que dar un abrazo a cualquier persona que te hable', opcion2: 'Siempre tener que dar un apretón de manos a cualquier persona que te hable' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender todos los lenguajes de programación', opcion2: 'Tener la capacidad de entender todos los lenguajes humanos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que usar un disfraz extravagante para cualquier ocasión', opcion2: 'Siempre tener que usar un disfraz que coincida con el tema de la ocasión' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier cosa en confeti', opcion2: 'Tener la capacidad de convertir cualquier cosa en pompas de jabón' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta cuando estás emocionado', opcion2: 'Siempre tener que moverte en cámara rápida cuando estás aburrido' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una conversación con un alienígena durante una hora', opcion2: 'Tener una conversación con un robot durante una hora' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer un baile antes de entrar a cualquier habitación', opcion2: 'Siempre tener que hacer una pirueta antes de entrar a cualquier habitación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que haga que las cosas cambien de color', opcion2: 'Tener un botón que haga que las cosas cambien de sabor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en acertijos', opcion2: 'Siempre tener que hablar en trabalenguas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender las conversaciones de los insectos', opcion2: 'Tener la capacidad de entender las conversaciones de las aves' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que usar gafas de sol, incluso en interiores', opcion2: 'Siempre tener que llevar un paraguas, incluso en días soleados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier objeto en un instrumento musical', opcion2: 'Tener la capacidad de transformar cualquier objeto en una obra de arte' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un video musical', opcion2: 'Siempre tener que moverte como si estuvieras en una película de comedia' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en una planta', opcion2: 'Tener la capacidad de convertir cualquier objeto en una mascota' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Siempre tener que comunicarte a través de mensajes escritos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de teletransportarte a cualquier lugar del mundo', opcion2: 'Tener la capacidad de volar a la velocidad de una bicicleta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que saludar a las personas con un saludo de una cultura diferente', opcion2: 'Siempre tener que saludar a las personas con un abrazo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el color de tus ojos según tu estado de ánimo', opcion2: 'Tener la capacidad de cambiar la forma de tus orejas según tu estado de ánimo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar con un acento extranjero', opcion2: 'Siempre tener que hablar como un personaje de película' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos cobren vida por un día', opcion2: 'Tener la capacidad de hacer que los objetos se conviertan en comida' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tener una conversación en voz alta contigo mismo', opcion2: 'Siempre tener que tener una conversación susurrante contigo mismo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las sombras cobren vida', opcion2: 'Tener la capacidad de hacer que los reflejos hablen' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en una película de acción', opcion2: 'Siempre tener que moverte como si estuvieras en un musical' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que saludar a los extraños con un chiste', opcion2: 'Siempre tener que saludar a los extraños con un cumplido' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier conversación en una canción', opcion2: 'Tener la capacidad de transformar cualquier conversación en una historia de terror' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta cuando estás emocionado', opcion2: 'Siempre tener que moverte muy rápido cuando estás nervoso' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de traducir los ladridos de los perros', opcion2: 'Tener la capacidad de traducir los maullidos de los gatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener un séquito de pingüinos siguiéndote', opcion2: 'Siempre tener un séquito de flamencos siguiéndote' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un reloj que te muestra cuánto tiempo te queda de vida', opcion2: 'Tener un reloj que te muestra cuántos actos de bondad has realizado' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer un salto mortal antes de sentarte en cualquier lugar', opcion2: 'Siempre tener que hacer un giro antes de levantarte de cualquier silla' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un cojín que siempre está en la temperatura perfecta', opcion2: 'Tener un cojín que emite sonidos relajantes cuando te sientas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tener una conversación seria con una marioneta', opcion2: 'Siempre tener que tener una conversación en tono cómico con un maniquí' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos inanimados', opcion2: 'Tener la capacidad de entender el lenguaje de las abejas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar una palabra en cada frase con "meow"', opcion2: 'Siempre tener que reemplazar una palabra en cada frase con "quack"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', opcion2: 'Tener un espejo que te muestra cómo serás en 20 años' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte haciendo moonwalk', opcion2: 'Siempre tener que moverte como si estuvieras en una pasarela' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender el lenguaje de los pájaros', opcion2: 'Tener la capacidad de entender el lenguaje de los insectos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en acertijos', opcion2: 'Siempre tener que hablar en trabalenguas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que cambia el clima solo en tu ubicación', opcion2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación telepática con los animales', opcion2: 'Tener la capacidad de comunicarte con las plantas a través de canciones' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar tus pensamientos en voz alta', opcion2: 'Siempre tener que hablar en un idioma inventado por ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', opcion2: 'Siempre tener que responder instantáneamente sin pensar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas gorila', opcion2: 'Tener un guardaespaldas flamenco' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', opcion2: 'Siempre tener que llevar un paraguas incluso en días despejados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una burbuja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', opcion2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', opcion2: 'Tener la capacidad de hacer que las cosas cambien de forma' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte haciendo moonwalk', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el color de tu piel como un camaleón', opcion2: 'Tener la capacidad de cambiar el patrón de tu piel como un cebra' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en verso', opcion2: 'Siempre tener que hablar en onomatopeyas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que cambia el clima solo en tu ubicación', opcion2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación telepática con los animales', opcion2: 'Tener la capacidad de comunicarte con las plantas a través de canciones' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar tus pensamientos en voz alta', opcion2: 'Siempre tener que hablar en un idioma inventado por ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', opcion2: 'Siempre tener que responder instantáneamente sin pensar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas gorila', opcion2: 'Tener un guardaespaldas flamenco' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', opcion2: 'Siempre tener que llevar un paraguas incluso en días despejados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una burbuja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', opcion2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', opcion2: 'Tener la capacidad de hacer que las cosas cambien de forma' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta durante las mañanas', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el color de tu piel como un camaleón', opcion2: 'Tener la capacidad de cambiar el patrón de tu piel como un cebra' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en verso', opcion2: 'Siempre tener que hablar en onomatopeyas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que cambia el clima solo en tu ubicación', opcion2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación telepática con los animales', opcion2: 'Tener la capacidad de comunicarte con las plantas a través de canciones' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar tus pensamientos en voz alta', opcion2: 'Siempre tener que hablar en un idioma inventado por ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', opcion2: 'Siempre tener que responder instantáneamente sin pensar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas gorila', opcion2: 'Tener un guardaespaldas flamenco' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', opcion2: 'Siempre tener que llevar un paraguas incluso en días despejados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una burbuja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', opcion2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', opcion2: 'Tener la capacidad de hacer que las cosas cambien de forma' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta durante las mañanas', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un video musical', opcion2: 'Siempre tener que moverte como si estuvieras en una película de acción' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un teletransportador que solo funciona si haces el moonwalk', opcion2: 'Tener un teletransportador que solo funciona si haces una pirueta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tatuaje temporal con un mensaje divertido', opcion2: 'Siempre tener que llevar un tatuaje temporal con un mensaje inspirador' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos electrónicos', opcion2: 'Tener la capacidad de comunicarte con las nubes a través de movimientos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que dar una pequeña actuación antes de tomar una foto', opcion2: 'Siempre tener que hacer una pose extravagante antes de tomar una foto' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en lenguaje de señas', opcion2: 'Siempre tener que comunicarte en lenguaje morse' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un sombrero que siempre reproduce música a tu alrededor', opcion2: 'Tener una bufanda que siempre te mantiene a la temperatura perfecta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar una pizarra y tiza para escribir mensajes', opcion2: 'Siempre tener que llevar una pizarra y imanes para escribir mensajes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender y hablar con los emojis', opcion2: 'Tener la capacidad de entender y hablar con los símbolos matemáticos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer beatbox cada vez que te saludan', opcion2: 'Siempre tener que tararear una canción cada vez que te saludan' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una colección de ropa de disfraces de tamaño mini para tus mascotas', opcion2: 'Tener una colección de sombreros elegantes de tamaño gigante para ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier situación en una escena de comedia', opcion2: 'Tener la capacidad de transformar cualquier situación en una escena de película de terror' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer beatbox mientras bailas', opcion2: 'Siempre tener que hacer palmas al ritmo mientras caminas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos desaparezcan temporalmente', opcion2: 'Tener la capacidad de hacer que los objetos se multipliquen temporalmente' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una nube personal que te sigue y te proporciona sombra', opcion2: 'Tener un séquito de mariposas que te siguen a todas partes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en rimas', opcion2: 'Siempre tener que comunicarte en poesía épica' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos cobren vida por un día', opcion2: 'Tener la capacidad de hacer que los objetos se conviertan en comida' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tener una conversación seria con una marioneta', opcion2: 'Siempre tener que tener una conversación en tono cómico con un maniquí' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos inanimados', opcion2: 'Tener la capacidad de entender el lenguaje de las abejas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar una palabra en cada frase con "meow"', opcion2: 'Siempre tener que reemplazar una palabra en cada frase con "quack"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', opcion2: 'Tener un espejo que te muestra cómo serás en 20 años' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte haciendo moonwalk', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar el color de tu piel como un camaleón', opcion2: 'Tener la capacidad de cambiar el patrón de tu piel como un cebra' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en verso', opcion2: 'Siempre tener que hablar en onomatopeyas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un botón que cambia el clima solo en tu ubicación', opcion2: 'Tener un botón que cambia la apariencia de las personas a tu alrededor' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hablar en voz alta lo que piensas', opcion2: 'Nunca más poder hablar en voz alta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de tener una conversación telepática con los animales', opcion2: 'Tener la capacidad de comunicarte con las plantas a través de canciones' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar tus pensamientos en voz alta', opcion2: 'Siempre tener que hablar en un idioma inventado por ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer una pausa dramática antes de responder cualquier pregunta', opcion2: 'Siempre tener que responder instantáneamente sin pensar' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un guardaespaldas gorila', opcion2: 'Tener un guardaespaldas flamenco' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un sombrero de sombrilla para protegerte del sol', opcion2: 'Siempre tener que llevar un paraguas incluso en días despejados' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir cualquier objeto en un globo', opcion2: 'Tener la capacidad de convertir cualquier objeto en una burbuja' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tomar el camino más largo para llegar a tu destino', opcion2: 'Siempre tener que tomar el camino más corto pero lleno de obstáculos divertidos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas cambien de tamaño', opcion2: 'Tener la capacidad de hacer que las cosas cambien de forma' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte en cámara lenta durante las mañanas', opcion2: 'Siempre tener que moverte a alta velocidad durante las tardes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en comida', opcion2: 'Tener la capacidad de leer los pensamientos de las personas solo cuando están pensando en música' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte con gestos y mímica', opcion2: 'Siempre tener que comunicarte a través de dibujos y garabatos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender los suspiros de las personas', opcion2: 'Tener la capacidad de entender los bostezos de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que resolver acertijos antes de poder abrir una puerta', opcion2: 'Siempre tener que hacer un baile antes de poder abrir una puerta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de cambiar la voz de las personas a tu antojo', opcion2: 'Tener la capacidad de cambiar el acento de las personas a tu antojo' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tutú en eventos formales', opcion2: 'Siempre tener que llevar una capa de superhéroe en eventos formales' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que las cosas leviten', opcion2: 'Tener la capacidad de hacer que las cosas se vuelvan pegajosas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que contar chistes malos antes de cualquier conversación', opcion2: 'Siempre tener que contar datos curiosos antes de cualquier conversación' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de saber qué canción está sonando en la cabeza de las personas', opcion2: 'Tener la capacidad de saber qué película está pasando en la mente de las personas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un video musical', opcion2: 'Siempre tener que moverte como si estuvieras en una película de acción' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un teletransportador que solo funciona si haces el moonwalk', opcion2: 'Tener un teletransportador que solo funciona si haces una pirueta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar un tatuaje temporal con un mensaje divertido', opcion2: 'Siempre tener que llevar un tatuaje temporal con un mensaje inspirador' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos electrónicos', opcion2: 'Tener la capacidad de comunicarte con las nubes a través de movimientos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que dar una pequeña actuación antes de tomar una foto', opcion2: 'Siempre tener que hacer una pose extravagante antes de tomar una foto' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de convertir tus sueños en películas animadas', opcion2: 'Tener la capacidad de convertir tus pensamientos en canciones populares' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en lenguaje de señas', opcion2: 'Siempre tener que comunicarte en lenguaje morse' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un sombrero que siempre reproduce música a tu alrededor', opcion2: 'Tener una bufanda que siempre te mantiene a la temperatura perfecta' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que llevar una pizarra y tiza para escribir mensajes', opcion2: 'Siempre tener que llevar una pizarra y imanes para escribir mensajes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de entender y hablar con los emojis', opcion2: 'Tener la capacidad de entender y hablar con los símbolos matemáticos' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer beatbox cada vez que te saludan', opcion2: 'Siempre tener que tararear una canción cada vez que te saludan' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una colección de ropa de disfraces de tamaño mini para tus mascotas', opcion2: 'Tener una colección de sombreros elegantes de tamaño gigante para ti' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de transformar cualquier situación en una escena de comedia', opcion2: 'Tener la capacidad de transformar cualquier situación en una escena de película de terror' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que hacer beatbox mientras bailas', opcion2: 'Siempre tener que hacer palmas al ritmo mientras caminas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos desaparezcan temporalmente', opcion2: 'Tener la capacidad de hacer que los objetos se multipliquen temporalmente' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que moverte como si estuvieras en un videojuego de plataformas', opcion2: 'Siempre tener que moverte como si estuvieras en un videojuego de baile' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener una nube personal que te sigue y te proporciona sombra', opcion2: 'Tener un séquito de mariposas que te siguen a todas partes' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que comunicarte en rimas', opcion2: 'Siempre tener que comunicarte en poesía épica' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hacer que los objetos cobren vida por un día', opcion2: 'Tener la capacidad de hacer que los objetos se conviertan en comida' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que tener una conversación seria con una marioneta', opcion2: 'Siempre tener que tener una conversación en tono cómico con un maniquí' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener la capacidad de hablar con los objetos inanimados', opcion2: 'Tener la capacidad de entender el lenguaje de las abejas' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Siempre tener que reemplazar una palabra en cada frase con "meow"', opcion2: 'Siempre tener que reemplazar una palabra en cada frase con "quack"' },
        { pregunta: '¿Qué prefieres 🤔?', opcion1: 'Tener un baúl que siempre contiene exactamente lo que necesitas', opcion2: 'Tener un espejo que te muestra cómo serás en 20 años' }
    ];

    // Recorre cada pregunta y agrega los documentos correspondientes en Firebase
    for (const preguntaData of preguntas) {
        // Crea un nuevo documento para la pregunta en la colección "questions"
        const preguntaDocRef = doc(collection(db, 'questions'));

        // Establece el campo "text" de la pregunta
        await setDoc(preguntaDocRef, { text: preguntaData.pregunta });

        // Crea un documento en la subcolección "option1" con la opción 1 y el contador inicial en 0
        const option1DocRef = doc(collection(preguntaDocRef, 'option1'));
        await setDoc(option1DocRef, {
            text: preguntaData.opcion1,
            count: 0,
        });

        // Crea un documento en la subcolección "option2" con la opción 2 y el contador inicial en 0
        const option2DocRef = doc(collection(preguntaDocRef, 'option2'));
        await setDoc(option2DocRef, {
            text: preguntaData.opcion2,
            count: 0,
        });

        console.log(`Pregunta ${preguntas.indexOf(preguntaData) + 1}/${preguntas.length} cargada`);
    }

    console.log('Preguntas cargadas exitosamente en Firebase Firestore');
};

// Llama a la función para cargar las preguntas
cargarPreguntas();
